# Generated by Django 3.2.4 on 2021-07-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herapp', '0002_briketkomur_mesekomur_nakliyefoto_pressosismangalkuru'),
    ]

    operations = [
        migrations.CreateModel(
            name='NargileKomuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='images')),
                ('resim_adi', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'NargileKömürResim',
                'verbose_name_plural': 'MangalKömürüResimleri',
            },
        ),
    ]
