# Generated by Django 3.2.4 on 2021-07-16 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herapp', '0003_nargilekomuru'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nargilekomuru',
            options={'verbose_name': 'NargileKömürResim', 'verbose_name_plural': 'NargileKömürüResimleri'},
        ),
    ]
