# Generated by Django 3.2.4 on 2021-07-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herapp', '0006_urunler'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Resim', 'verbose_name_plural': 'AnasayfadaPaylaşılanResimler'},
        ),
    ]
